@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.data}}
### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/

###

# @name Recados

GET {{baseUrl}}/recados/?page=1&limit=10

###

GET {{baseUrl}}/recados/7/

###

POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "Teste novo",
  "de": 6,
  "para": 7
}

###

PUT {{baseUrl}}/recados/1/
Content-Type: application/json

{
  "texto": "Teste editado",
  "de": "Eu",
  "para": "Você",
  "lido": false
}

###

DELETE  {{baseUrl}}/recados/6/

@baseUrl = http://localhost:3000

###

# @name pessoas

GET {{baseUrl}}/pessoas/?page=1&limit=10
Authorization: Bearer {{authToken}}

###

GET {{baseUrl}}/pessoas/1/
Authorization: Bearer {{authToken}}
###

POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "email": "teste2@teste.com",
  "name": "Eauaaa",
  "password": "senha"
}

###

PATCH {{baseUrl}}/pessoas/6/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "dsadsa",
  "password": "Vocêaaa"
}

###

DELETE  {{baseUrl}}/pessoas/4/
Authorization: Bearer {{authToken}}

###

# @name authenticate

POST {{baseUrl}}/auth/
Content-Type: application/json

{
  "email": "teste2@teste.com",
  "password": "senha"
}