@baseUrl = http://localhost:3000
### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/

###

# @name Recados

GET {{baseUrl}}/recados/?page=1&limit=10

###

GET {{baseUrl}}/recados/1/

###

POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "Teste novo",
  "de": "Eauaaa",
  "para": "Vocêaaa"
}

###

PUT {{baseUrl}}/recados/1/
Content-Type: application/json

{
  "texto": "Teste editado",
  "de": "Eu",
  "para": "Você",
  "lido": false
}

###

DELETE  {{baseUrl}}/recados/1/

@baseUrl = http://localhost:3000

###

# @name pessoas

GET {{baseUrl}}/pessoas/?page=1&limit=10

###

GET {{baseUrl}}/pessoas/1/

###

POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "email": "ads@teste.com",
  "name": "Eauaaa",
  "password": "Vocêaaa"
}

###

PATCH {{baseUrl}}/pessoas/6/
Content-Type: application/json

{
  "name": "dsadsa",
  "password": "Vocêaaa"
}

###

DELETE  {{baseUrl}}/pessoas/4/