name: nest-js-basics

services:
  db:
    image: postgres:18.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5433:5432"

volumes:
  postgres-data: